name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Conectar via SSH e fazer deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Clona o repositório se ainda não existir
          if [ ! -d "Data-Ops-Atividade-III" ]; then
            git clone https://github.com/Luigi052/Data-Ops-Atividade-III.git
          fi

          cd Data-Ops-Atividade-III
          git pull origin main

          # Para e remove o container antigo, se existir
          sudo docker stop calculadora || true
          sudo docker rm calculadora || true

          # Faz o build com contexto na raiz e Dockerfile na pasta app/
          sudo docker build -t calculadora -f app/Dockerfile .

          # Sobe o novo container na porta 80
          sudo docker run -d -p 80:80 --name calculadora calculadora
