name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Conectar via SSH e fazer deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/seu-projeto || git clone https://github.com/SEU_USUARIO/SEU_REPO.git ~/seu-projeto && cd ~/seu-projeto
          git pull origin main
          docker stop calculadora || true
          docker rm calculadora || true
          docker build -t calculadora .
          docker run -d -p 80:80 --name calculadora calculadora
